      FUNCTION INTEGRAND (X)
      IMPLICIT NONE
      DOUBLE PRECISION X
      DOUBLE PRECISION INTEGRAND
      INTEGRAND = X**2 + 4.*X - 12.
      END FUNCTION INTEGRAND
      
      FUNCTION INTEGRAL (X1,X2)
      IMPLICIT NONE
      DOUBLE PRECISION X1, X2
      DOUBLE PRECISION INTEGRAL
      INTEGRAL = X2**3/3. + 2.*X2**2 - 12.*X2 -
     &          (X1**3/3. + 2.*X1**2 - 12.*X1)
      END FUNCTION

      PROGRAM TEST
      IMPLICIT NONE
      DOUBLE PRECISION A, B, EPSABS, EPSREL, RESULT, ABSERR
      INTEGER KEY, NEVAL, IER, LIMIT, LENW, LAST
      PARAMETER (LIMIT = 50, LENW = 200)
      INTEGER IWORK(LIMIT)
      DOUBLE PRECISION WORK(LENW)
      EXTERNAL DQAGS, INTEGRAND, INTEGRAL
      DOUBLE PRECISION INTEGRAL
      A = -1.
      B = 1.
      EPSABS = 1E-3
      EPSREL = 1E-3
      KEY = 1
      CALL DQAGS(INTEGRAND,A,B,EPSABS,EPSREL,
     &     RESULT, ABSERR, NEVAL, IER, LIMIT, LENW, LAST, IWORK, WORK)
      PRINT *, 'Answers: '
      PRINT *, RESULT, ABSERR, NEVAL, IER
      PRINT *, 'Test against analytic function'
      PRINT *, INTEGRAL(A,B)
      END PROGRAM TEST
